### ISSUE TITLE
How about update your readme file.

### ISSUE THREAD

**Issue by darkrasid** [brandicted/ramses#91]
Hi. 
I have interest to your project. And I want to suggest one thing.

I find your project via elasticsearch blog ([this article](https://www.elastic.co/blog/make-an-elasticsearch-powered-rest-api-for-any-data-with-ramses))
And I try to understand what the project do and how can I get some advantage using the project.  
However it's very hard to find docs about the advantage of ramses. 

How about describe some reasons why many people should use ramses in README file.  
Maybe more people can use ramses more easily.

**Comment by jstoiko** [comment]
Thank you @darkrasid, that's a great suggestion! We'll for sure take it into consideration. Maybe you can help us.

We recently put a one-page marketing website: http://ramses.tech and here's the documentation: https://ramses.readthedocs.org

After looking at these two links, in one sentence, how would you describe Ramses in a way that is easy to understand by anyone?

**Comment by jstoiko** [comment]
http://ramses.tech has more "first glance" info now. It then invites users to "Get started" which brings to the docs for hand-on tutorials.

Closing.
